#!/bin/sh

start() {
  echo -n "Starting Android properties: "

  echo 0 > /proc/sys/kernel/hung_task_timeout_secs
  echo 0 > /sys/block/mmcblk0boot0/force_ro
  echo 0 > /sys/block/mmcblk0boot1/force_ro

  [ $? = 0 ] && echo "OK" || echo "FAIL"
}
stop() {
  echo -n "Stopping Android properties: "
  [ $? = 0 ] && echo "OK" || echo "FAIL"
}
restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
