#!/bin/sh

start() {
  echo -n "Starting boot menu: "
  /bootmenu.py
}
stop() {
  echo -n "Stopping boot menu: "
  [ $? = 0 ] && echo "OK" || echo "FAIL"
}
restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
